### ISSUE TITLE
Pending deprecation on arrow.get()

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#264]
Arrow 0.15 is potentially going to break some of the current usage of `arrow.get()`:

```
/Users/fluffy/.local/share/virtualenvs/.../lib/python3.7/site-packages/arrow/factory.py:202:
ArrowParseWarning: The .get() parsing method without a format string will parse more strictly in
version 0.15.0.See https://github.com/crsmithdev/arrow/issues/612 for more details.
```

Relevant issue: https://github.com/crsmithdev/arrow/issues/612

**Comment by systemcatch** [comment]
Hi @fluffy-critter I'm one of the maintainers of arrow. If you can show me the type of time format Publ uses I can tell you if any changes will need to be made on your end.

**Comment by fluffy-critter** [comment]
Publ allows users to enter dates in a free form manner and this issue is just to remind myself to ensure that errors are handled correctly. I’m not concerned about any issues coming from Publ itself, I just want to make sure I file off the rough edges for others. :)

Thanks, though!

**Comment by fluffy-critter** [comment]
I did an audit and the only place where `arrow.get` is used in this way is in a context where `ParserError` gets caught specifically because I needed to handle malformed dates already. :) So I'm changing this issue to be "blocked external" so I can remove the warning removal when arrow 0.15.0 is released.

We can remove https://github.com/PlaidWeb/Publ/blob/master/publ/__init__.py#L22 and the related `import arrow.factory` when this happens.

**Comment by fluffy-critter** [comment]
Missed a spot: https://github.com/PlaidWeb/Publ/blob/master/publ/utils.py#L92

**Comment by fluffy-critter** [comment]
Oh wait never mind, that function is intended to raise an error if it fails to parse anyway.

**Comment by fluffy-critter** [comment]
This has been long-since resolved.
