### ISSUE TITLE
Add image cropping function

### ISSUE THREAD

**Issue by fluffy-critter** [PlaidWeb/Publ#77]
## Expected Behavior

Given an image argument of `crop=(l,t,r,b)` the image should be cropped to that box before it gets sent along to the resize logic.

## Context

Useful for authored thumbnails in galleries.

**Comment by karinassuni** [comment]
https://github.com/PlaidWeb/Publ/pull/169 implements cropping for LocalImages.

(Note that, in the output path spec, I have the cropping info before the size info, but we can totally change that if you want.)

From here, it looks to me like ExternalImage manipulations are done via CSS, and from cursory research it looks like cropping with pure CSS can only be done with the [help of a container element](https://stackoverflow.com/questions/7777159/clip-crop-background-image-with-css) or via the relatively new [object-fit property](https://alligator.io/css/cropping-images-object-fit/). Let me know what you think about possible ways to crop ExternalImages, or if you want to support that at all.
